# Generated by Django 4.2.7 on 2024-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_news_options_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_images/default_news.png', upload_to='news_images/'),
        ),
    ]
